name: Compilar Plugin ASI (32-bit)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  # Optamos por Node.js 24 para evitar los avisos de deprecación
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4 # Esta versión ya es compatible con el cambio de entorno

    - name: Configurar MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Configurar CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -A Win32

    - name: Compilar el proyecto
      run: cmake --build build --config Release

    - name: Subir el archivo .asi
      uses: actions/upload-artifact@v4
      with:
        name: PathFix-32bit
        path: build/Release/PathFix.asi
